# Site settings
title: The Daily Dialectic
email: d.kinkead@uq.edu.au
description: "Bite sized chunks of public philosophy served (almost) daily"

# Custom
collections:
  bites:
    output: true
    permalink: bites/:path/

# Build settings
markdown: kramdown
permalink: :title
